services:
  ml-dev:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
      - ./models:/app/models:ro
    ports:
      - "8000:8000"
